# -*- coding: cp1254 -*-
imods = [
    ("plain", "Plain"),
    ("cracked", "Cracked"),
    ("rusty", "Rusty"),
    ("bent", "Bent"),
    ("chipped", "Chipped"),
    ("battered", "Battered"),
    ("poor", "Poor"),
    ("crude", "Crude"),
    ("old", "Old"),
    ("cheap", "Cheap"),
    ("fine", "Fine"),
    ("well_made", "Well Made"),
    ("sharp", "Sharp"),
    ("balanced", "Balanced"),
    ("tempered", "Tempered"),
    ("deadly", "Deadly"),
    ("exquisite", "Exquisite"),
    ("masterwork", "Masterwork"),
    ("heavy", "Heavy"),
    ("strong", "Strong"),
    ("powerful", "Powerful"),
    ("tattered", "Tattered"),
    ("ragged", "Ragged"),
    ("rough", "Rough"),
    ("sturdy", "Sturdy"),
    ("thick", "Thick"),
    ("hardened", "Hardened"),
    ("reinforced", "Reinforced"),
    ("superb", "Superb"),
    ("lordly", "Lordly"),
    ("lame", "Lame"),
    ("swaybacked", "Swaybacked"),
    ("stubborn", "Stubborn"),
    ("timid", "Timid"),
    ("meek", "Meek"),
    ("spirited", "Spirited"),
    ("champion", "Champion"),
    ("fresh", "Fresh"),
    ("day_old", "Day Old"),
    ("two_day_old", "Two Day Old"),
    ("smelling", "Smelling"),
    ("rotten", "Rotten"),
    ("large_bag", "Large Bag"),
]
